### ISSUE TITLE
Polly

### ISSUE THREAD

**Issue by hockeymikey** [zakius/laravel-docker#1]
Again, you never explained why the project was deleted or what Waterfox has to do with anything.
https://github.com/zakius/Polly/pull/3
Please send me an email or other medium of your choosing if that would be easier/better.

**Comment by zakius** [comment]
I said all I have to say, if you need more ask r/waterfox mods

**Comment by hockeymikey** [comment]
@zakius Wish I could but they are abusive over there and I'm muted for 3 days. And I want your side of the story, not theirs.
